### ISSUE TITLE
Matmul not supported by esp-dl

### ISSUE THREAD

**Issue by karthikloganlogan** [alibukharai/Blogs#4]
How to resolve this, since everything in neural networks is based on matric multiplication. Even in the official documentation it still wasnt resolved. How did you run this model. Error is ,
Generating the quantization table:
MatMul is not supported on esp-dl yet
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/esp/calibration_pickle_file_testing.py", line 33, in <module>
    calib.generate_quantization_table(model_proto,calib_dataset, pickle_file_path)
  File "calibrator.py", line 344, in calibrator.Calibrator.generate_quantization_table
  File "calibrator.py", line 231, in calibrator.Calibrator.generate_output_model
  File "calibrator.py", line 226, in calibrator.Calibrator.check_model
ValueError: current model is not supported by esp-dl

**Comment by alibukharai** [comment]
@karthikloganlogan 
Please give me more context of the error. 
1- Which version of the idf are you using? --> **(Please use idf verison 4.4)** 
2- are you using your own model or find difficulty in using my model form training.

**Comment by karthikloganlogan** [comment]
1.The default idf i am using is 4.4.*
2.I used both your model as well as my model. Both showing me same error , ie ValueError: current model is not supported by esp-dl. The output when I run your model is,
Generating the quantization table:
MatMul is not supported on esp-dl yet
Traceback (most recent call last):
File "/home/ubuntu/PycharmProjects/esp/calibration_pickle_file_testing.py", line 33, in
calib.generate_quantization_table(model_proto,calib_dataset, pickle_file_path)
File "calibrator.py", line 344, in calibrator.Calibrator.generate_quantization_table
File "calibrator.py", line 231, in calibrator.Calibrator.generate_output_model
File "calibrator.py", line 226, in calibrator.Calibrator.check_model
ValueError: current model is not supported by esp-dl

**Comment by alibukharai** [comment]
@karthikloganlogan Please give me more context or share a github link with me. I will try to reproduce your error. I have checked the system on myside. Everything is working fine.
